version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: graph_api
      POSTGRES_USER: graph_user
      POSTGRES_PASSWORD: graph_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    restart: always

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    command: >
     # better to migrate manually 
      sh -c "
        # python manage.py migrate --settings=graph_api.settings.production &&
        gunicorn graph_api.wsgi:application --bind 0.0.0.0:8000
      "

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    depends_on:
      - db
      - redis
    env_file:
      - ../.env
    command: celery -A graph_api worker --loglevel=info

volumes:
  postgres_data:
