# Generated by Django 5.2.4 on 2025-08-03 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The unique name of the node",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nodes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        help_text="The source node of the connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="nodes.node",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        help_text="The target node of the connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "db_table": "connections",
                "ordering": ["-created_at"],
                "unique_together": {("from_node", "to_node")},
            },
        ),
    ]
