# Generated by Django 5.2.4 on 2025-08-02 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
